import type { MarketplaceShop } from '@/lib/shops';

export const mockMarketplaceShops: MarketplaceShop[] = [
  {
    id: '11111111-1111-1111-1111-111111111111',
    name: 'Navaja Centro',
    slug: 'navaja-centro',
    timezone: 'America/Montevideo',
    description: 'Cortes clasicos, agenda online y staff activo.',
    phone: '+5980000001',
    isVerified: true,
    logoUrl: null,
    coverImageUrl: null,
    imageUrls: [],
    locationLabel: 'Centro',
    city: 'Montevideo',
    region: 'Montevideo',
    countryCode: 'UY',
    latitude: -34.9011,
    longitude: -56.1645,
    reviewCount: 18,
    averageRating: 4.8,
    activeServiceCount: 4,
    minServicePriceCents: 900,
    customDomain: null,
    domainStatus: null,
    plan: 'free',
    subscriptionStatus: 'active',
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    name: 'Navaja Pocitos',
    slug: 'navaja-pocitos',
    timezone: 'America/Montevideo',
    description: 'Reservas y cursos dentro del marketplace.',
    phone: '+5980000002',
    isVerified: false,
    logoUrl: null,
    coverImageUrl: null,
    imageUrls: [],
    locationLabel: 'Pocitos',
    city: 'Montevideo',
    region: 'Montevideo',
    countryCode: 'UY',
    latitude: -34.9167,
    longitude: -56.1503,
    reviewCount: 6,
    averageRating: 4.4,
    activeServiceCount: 2,
    minServicePriceCents: 1100,
    customDomain: null,
    domainStatus: null,
    plan: 'free',
    subscriptionStatus: 'active',
  },
];
